version: v2
global: # defines default properties for the `tasks`
  runner:
    os_image: ubuntu

tasks:
  deploy-or-upload-to-az-static-website:
    steps:
      - checkout
      - commands:
        - az login --service-principal -u $APP_ID -p $PASS --tenant $TENANT
        - az storage blob upload-batch -s . -d '$web' --account-name razorops --overwrite true
